config/routes.rb
require 'domains'

Rails.application.routes.draw do

  # Agents admin
  namespace :admin do            
    resource :account_settings, path: 'settings', :constraints => Subdomain do
      get :tickets
      get :articles
      get :canned_responses
      get :rules
      get :labels
      get :imports
      get :registration
      get :roles
      get :permission_schemes
      post :import_tickets
      post :import_users
      post :import_replies
    end
    resources :canned_responses, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :rule_sets, :constraints => Subdomain
    resources :labels, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :roles, only: [:update, :create, :destroy, :edit], :constraints => Subdomain do
      post :add_user, on: :collection
      post :remove_user, on: :collection
    end
    resources :permissions, :constraints => Subdomain
    resources :permission_schemes, :constraints => Subdomain
    resources :channel_items, :constraints => Subdomain, only: [:index, :update, :destroy], path: 'channels' do
      get :create_ticket, on: :member
      get :sync, on: :collection
    end
    resources :products, param: :slug, :constraints => Subdomain do
      get :branding, on: :member
      get :permissions, on: :member
      get :users, on: :member
      post :update_user_roles, on: :member
      get :envato, on: :member
    end
    resources :users, param: :username  do
      get :import, on: :collection
      get :sync_envato_purchases, on: :member
      resources :user_settings, path: 'settings', only: [:update, :create]
    end
    resources :categories, :constraints => Subdomain do
      # put :move_article, on: :member
      collection do
        match :sync, :via => [:get, :post]
      end
    end
    resources :tickets, :constraints => Subdomain do
      get :import, on: :collection
      get :follow, on: :member
      get :unfollow, on: :member
      patch :update_status, on: :member
      patch :assign, on: :member
      resources :replies, shallow: true
    end
    resources :articles, :constraints => Subdomain do
      post :move, on: :member
    end
    resources :sections, only: [:index, :new, :create, :update, :edit, :destroy, :show], :constraints => Subdomain do
      put :sort, on: :collection
      put :sort_articles, on: :member
      post :move, on: :member
    end
  end
  root to: "products#index", :as => 'categories_index', :constraints => Subdomain

  # Tenant frontend
  resources :tickets, :constraints => Subdomain  
  resources :media, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
  resources :categories, only: [:show, :index], :constraints => Subdomain
  resources :articles #, :only => [:show], :constraints => Subdomain
  resources :search, only: [:index], :constraints => Subdomain
  devise_for :users, path: '', controllers: { sessions: "sessions", registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  mount Payola::Engine => '/payola', as: :payola
  get 'pricing' => 'subscriptions#show', as: 'pricing'
  resource :account, only: [:new, :create]
  resource :subscription, only: [:show] do #, :constraints => RootDomain do
    # get :create
    post :cancel
    post :change_plan
    patch :update_card
    resources :subscriptions
  end
  mount StripeEvent::Engine => '/webhooks', :constraints => RootDomain
  resources :products, param: :slug, path: '/', only: [:index, :show], :constraints => Subdomain

  # Landing
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', :constraints => RootDomain
  root to: "pages#show", :slug => 'home', :constraints => RootDomain
  resources :posts, only: [:index, :show, :edit, :update], param: :slug, path: 'blog', :constraints => RootDomain
  resources :pages, only: [:show, :edit, :update], param: :slug, path: '', :constraints => RootDomain
  
end

app/models/section.rb
class Section < ApplicationRecord
	acts_as_tenant(:account)

  include Filterable

  has_many :articles
  default_scope { ordered_by_position_asc }
  validates_presence_of :name
  acts_as_sortable
  scope :with_published_articles_for_item, -> (item) {
    includes(:articles).where(articles: {status: 'published', id: item.articles_items.pluck(:article_id)})
  }
  scope :title, -> (title) { where("name like ?", "%#{title}%")}


  def to_param
    "#{id}-#{self.name.parameterize}"
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
  include RequireTenant
  before_action :set_section, only: [:show, :edit, :update, :destroy, :move]
  layout 'admin'  

  # GET /sections
  # GET /sections.json
  def index
    @section = Section.new
    @sections = Section.filter(filtering_params(params)).paginate(:page => params[:page])
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
      @categories = Category.all
      @section = Section.includes(:articles).find(params[:id])
  end

  # PUT /sections/sort
  def sort
    params[:order].each_with_index do |value,index|
      next if value == "NULL"
      Section.find(value).update_attribute(:sort_order,index)
    end
    render :success => true
  end

  # PUT /sections/1/sort_articles
  def sort_articles
    params[:order].each_with_index do |value,index|
      next if value == "NULL"
      @article_item = ArticlesItem.find_by(section_id: params[:id], article_id: value.to_i)
      @article_item.sort_order = index
      if @article_item.save
        # render :success => true
      end
    end
  end

  # POST /sections/1/move
  def move
    @section.move_to! params[:position]
  end

  # GET /sections/new
  def new
    @section = Section.new
    session[:return_to] = request.referer
  end

  # GET /sections/1/edit
  def edit
    # @articles = Article.where(section_id: @section.id).ordered_by_position_asc
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to session[:return_to], notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    if @section.update(section_params)
      flash[:success] = 'Section updated.'
    else
      flash[:errors] = @section.errors.full_messages.join('<br>')
    end
    redirect_to :back
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :sort_order, :item_id)
    end

    # A list of the param names that can be used for filtering
    def filtering_params(params)
      params.slice(:title)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
	def section_item_url(section)
		if @item
			section_url(section) + '?item=' + @item.id.to_s
		else
			section_url(section)
		end
	end
end

app/views/admin/sections/_form.html.erb
<%= simple_form_for([:admin,@section]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/sections/_list.html.erb
<table class="sections table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |section| %>
      <tr class="section" data-url="<%= admin_section_path(section) %>">
        <td>
          <%= section.name %>
        </td>
        <td>
          <%= section.position %>
        </td>
        <td class="actions">
          <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_admin_section_path(section), :remote => true  %>
          <%= link_to '<i class="material-icons">delete</i>'.html_safe, admin_section_path(section), method: :delete, data: { confirm: 'Are you sure?  This will delete the section and all associated articles.' }, :remote => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/sections/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="actions-bar">
				<%= link_to '<i class="material-icons">add</i> New Article'.html_safe, new_article_path, :class => 'btn btn-primary' %>
			</div>
			<h1><%= @section.name %></h1>
			<%= render 'form', section: @section %>
		</div>
	</div>
</div>

app/views/admin/sections/edit.js.erb
renderModal('section-modal', '<%= escape_javascript(render 'form') %>');

app/views/admin/sections/index.html.erb
<div class="row">
  <div class="col-lg-2 sidebar">
  	<h5>Filter Sections</h5>
  	<div class="filters">
  	  <%= simple_form_for @section, :url => admin_sections_url(:status => params[:status]), :method => :get, html: { id: :sections_filter } do |f| %>
  	    <%= f.input :name, selected: params[:title], input_html: { name: :title } %>
  	  <% end %>
  	</div>
  </div>

  <main class="col-lg-9">
    <div class="page-header">
      <h1 class="page-title">Sections</h1>
    </div>
    <%= render 'list' %>

  </main>
  <%= will_paginate @sections %>
  

</div>

app/views/admin/sections/index2.html.erb
<ol class="breadcrumb">
  <li class="active">
    Sections
  </li>
</ol>
<div class="container">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="actions-bar">
				<%= link_to '<i class="material-icons">add</i> New Section'.html_safe, new_section_path, class: 'btn btn-primary' %>
			</div>
			<p class="alert alert-info">Drag and drop the sections below to reorder how they appear in your knowledge base.</p>
			<ol data-role="activerecord_sortable">
			<%# @sections = @sections.reject{ |s| s.id == 3} %>
			  <% @sections.each do |section| %>

			  <li data-role="section<%= section.id %>" data-move-url="<%= move_section_url(section) %>" data-position="<%= section.position %>" class="<%#= 'hidden-xs-up' if section.id == 3 %>">
			  	<div class="row">
  				  <!-- <i class="material-icons handle">import_export</i> -->
  				  <i class="material-icons handle">drag_handle</i>
			  		<div class="col-md-8">
	  			    <h5><%= link_to section.name, edit_section_path(section) %></h5>
			  		</div>
			  		<div class="col-md-4 text-right">
  			    	<div class="actions">
  					    <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_section_path(section) %>
  					    <%= link_to '<i class="material-icons">delete</i>'.html_safe, section, method: :delete, data: { confirm: 'Are you sure?' } %>
  			    	</div>
			  		</div>
			  	</div>


			  </li>
			  <% end %>
			</ol>
		</div>
	</div>

</div>

app/views/admin/sections/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 offset-md-4">
		<div class="page-header">
			<h1>New Section</h1>
		</div>
		<div class="card">
			<div class="card-block">
				<%= render 'form', section: @section %>
			</div>
		</div>


		</div>
	</div>
</div>

app/views/admin/sections/show.html.erb
<% content_for :page_header do %>
  <h1>Articles</h1>
<% end %>
<%= render 'admin/categories/sidebar'%>
<div class="content">
    <%= render 'admin/articles/list', articles: @section.articles %>
</div>

app/views/admin/sections/update.js.erb
$('#section-modal').modal('hide');
Turbolinks.replace