config/routes.rb
require 'domains'

Rails.application.routes.draw do

  # Agents admin
  namespace :admin do            
    resource :account_settings, path: 'settings', :constraints => Subdomain do
      get :tickets
      get :articles
      get :canned_responses
      get :rules
      get :labels
      get :imports
      get :registration
      get :roles
      get :permission_schemes
      post :import_tickets
      post :import_users
      post :import_replies
    end
    resources :canned_responses, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :rule_sets, :constraints => Subdomain
    resources :labels, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :roles, only: [:update, :create, :destroy, :edit], :constraints => Subdomain do
      post :add_user, on: :collection
      post :remove_user, on: :collection
    end
    resources :permissions, :constraints => Subdomain
    resources :permission_schemes, :constraints => Subdomain
    resources :channel_items, :constraints => Subdomain, only: [:index, :update, :destroy], path: 'channels' do
      get :create_ticket, on: :member
      get :sync, on: :collection
    end
    resources :products, param: :slug, :constraints => Subdomain do
      get :branding, on: :member
      get :permissions, on: :member
      get :users, on: :member
      post :update_user_roles, on: :member
      get :envato, on: :member
    end
    resources :users, param: :username  do
      get :import, on: :collection
      get :sync_envato_purchases, on: :member
      resources :user_settings, path: 'settings', only: [:update, :create]
    end
    resources :categories, :constraints => Subdomain do
      # put :move_article, on: :member
      collection do
        match :sync, :via => [:get, :post]
      end
    end
    resources :tickets, :constraints => Subdomain do
      get :import, on: :collection
      get :follow, on: :member
      get :unfollow, on: :member
      patch :update_status, on: :member
      patch :assign, on: :member
      resources :replies, shallow: true
    end
    resources :articles, :constraints => Subdomain do
      post :move, on: :member
    end
    resources :sections, only: [:index, :new, :create, :update, :edit, :destroy, :show], :constraints => Subdomain do
      put :sort, on: :collection
      put :sort_articles, on: :member
      post :move, on: :member
    end
  end
  root to: "products#index", :as => 'categories_index', :constraints => Subdomain

  # Tenant frontend
  resources :tickets, :constraints => Subdomain  
  resources :media, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
  resources :categories, only: [:show, :index], :constraints => Subdomain
  resources :articles #, :only => [:show], :constraints => Subdomain
  resources :search, only: [:index], :constraints => Subdomain
  devise_for :users, path: '', controllers: { sessions: "sessions", registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  mount Payola::Engine => '/payola', as: :payola
  get 'pricing' => 'subscriptions#show', as: 'pricing'
  resource :account, only: [:new, :create]
  resource :subscription, only: [:show] do #, :constraints => RootDomain do
    # get :create
    post :cancel
    post :change_plan
    patch :update_card
    resources :subscriptions
  end
  mount StripeEvent::Engine => '/webhooks', :constraints => RootDomain
  resources :products, param: :slug, path: '/', only: [:index, :show], :constraints => Subdomain

  # Landing
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', :constraints => RootDomain
  root to: "pages#show", :slug => 'home', :constraints => RootDomain
  resources :posts, only: [:index, :show, :edit, :update], param: :slug, path: 'blog', :constraints => RootDomain
  resources :pages, only: [:show, :edit, :update], param: :slug, path: '', :constraints => RootDomain
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  include Payola::StatusBehavior
  layout :tenant_or_frontend

  before_action :find_plan_coupon_quantity_and_trial_end, only: [:create, :change_plan]
  before_action :confirm_max_agents, only: [:create, :change_plan]
  before_filter :set_subscription, only: [:show]
  before_filter :load_plans, only: [:show, :index]

  def create
    owner = current_tenant
    params[:plan] = @plan
    subscription = Payola::CreateSubscription.call(params, owner)
    flash[:success] = 'You\'ve successfully subscribed!'
    render_payola_status(subscription)
  end

  def cancel
    subscription = current_tenant.subscription
    Payola::CancelSubscription.call(subscription, at_period_end: true)
    flash[:success] = 'Your subscription has been canceled.'
    redirect_to :back
  end

  def change_plan
    @subscription = current_tenant.subscription
    Payola::ChangeSubscriptionPlan.call(@subscription, @plan, @quantity, @coupon)
    @subscription.cancel_at_period_end = false
    if @subscription.save
      flash[:success] = 'Your subscription plan has been updated.'
      redirect_to :back
    else
      flash[:error] = 'There was a problem updating your subscription.'
    end
  end

  private

    def set_subscription
      if current_tenant.subscription
        @subscription = current_tenant.subscription
      else
        @subscription = current_tenant.build_subscription
      end
    end

    def load_plans
      @subscription_plans = SubscriptionPlan.order(:id)
    end

    def confirm_max_agents
      if @quantity < User.total_agents
        flash[:error] = 'You have too many agents.  Please add more to your plan or remove agents from your account.'
        redirect_to :back
      end
    end

    def find_plan_coupon_quantity_and_trial_end
      find_plan
      find_coupon
      find_trial_end
      find_quantity
    end

    def find_plan
      @plan = SubscriptionPlan.find_by!(id: params[:plan_id])
    end

    def find_coupon
      @coupon = cookies[:cc] || params[:cc] || params[:coupon_code] || params[:coupon]
    end

    def find_trial_end
      @trial_end = params[:trial_end]
    end

    def find_quantity
      @quantity = params[:quantity].blank? ? 1 : params[:quantity].to_i
    end
    
    def tenant_or_frontend
      if current_tenant
        "application"
      else
        "frontend"
      end
    end
end

app/views/subscriptions/new.html.erb
 <!-- this header can go in <head> or at the bottom of <body> -->
<%= render 'payola/transactions/stripe_header' %>

<%= form_tag('/subscription',
      class: 'payola-onestep-subscription-form',
      'data-payola-base-path' => '/payola',
      'data-payola-plan-type' => @plan.plan_class,
      'data-payola-plan-id' => @plan.id
  ) do |f| %>
  <span class="payola-payment-error"></span>
  Email:<br>
  <input type="email" name="stripeEmail" data-payola="email"></input><br>
  Card Number<br>
  <input type="text" data-stripe="number"></input><br>
  Exp Month<br>
  <input type="text" data-stripe="exp_month"></input><br>
  Exp Year<br>
  <input type="text" data-stripe="exp_year"></input><br>
  CVC<br>
  <input type="text" data-stripe="cvc"></input><br>
  <input type="submit"></input>
<% end %>
<%#= render 'card', title: (Koudoku.free_trial? ? t('koudoku.subscriptions.start_trial') : t('koudoku.subscriptions.upgrade_your_account')), url: owner_subscriptions_path(@owner) %>

app/views/subscriptions/show.html.erb
<div class="container">
	<div class="page-header">
		<div class="actions-bar">
			<% if @subscription.plan_id %>
				<%= link_to '<i class="material-icons">cancel</i> Cancel Subscription'.html_safe, cancel_subscription_path, class: 'btn btn-white',  data: { confirm: 'Your subscription will be cancelled at the end of this billing cycle.  Are you sure you want to cancel?' }, method: :post %>
				<%= link_to '<i class="material-icons">credit_card</i> Update Card'.html_safe, '#', class: 'btn btn-white', data: { toggle: "modal", target: "#update-card-modal" } %>
			<% end %>
		</div>
	</div>
</div>


<div class="container">
  <div class="pricing-table row">

    <div class="col-md-4">
      <% if @subscription.plan_id %>
        <h1><%= @subscription.plan.name %> Plan</h1>
        <p>You're currently subscribed to the <%= @subscription.plan.name %> plan with <%= pluralize(@subscription.quantity, 'agent') %>.</p>
        <p>To change plans, simply select the number of agents you'd like to have under the respective plan.</p>
      <% elsif current_tenant %>
        <h1><%= pluralize(current_tenant.trial_days_left, 'trial day') %> left</h1>
        <p>You can subscribe to a plan at any time by selecting one from the right.</p>
      <% else %>
        <h1>Work smarter.<br/>Not harder.</h1>
        <p>Your support system should work for you.  Get happier customers and increase your sales!</p>
      <% end %>

      <% if @subscription.cancel_at_period_end %>
        <div class="alert alert-danger">Your subscription will be cancelled at the end of this billing cycle.</div>
      <% end %>
    </div>

    <% @subscription_plans.each do |plan| %>
      <div class="col-md-4">
        <div class="plan card">
          <div class="thumbnail">
            <div class="caption">
              <h3><%= plan.name %></h3>
              <h4 data-base-price="<%= plan.price %>"><%= plan.price %></h4>
              <div class="call-to-action">
                <%= form_tag (@subscription.plan_id.nil? ? subscription_path : change_plan_subscription_path) do |f| %>
                  <input type="number" name="quantity" class="subscription_quantity" value="<%= @subscription.quantity.nil? ? '1' : @subscription.quantity %>" min="1"> <span class="agent-noun">agent</span>
                  <input type="hidden" name="plan_class" id="plan_class" value="subscription_plan">
                  <input type="hidden" name="plan_id" class="subscription_plan_id" value="<%= plan.id %>">
                  <input type="hidden" name="plan_name" class="subscription_plan_name" value="<%= plan.name %>">
                  <% if @subscription.plan_id.nil? %>
                    <button type="button" class="btn btn-primary subscription-btn" data-toggle="modal" data-target="#subscription-modal">
                      Subscribe
                    </button>
                  <% else %>
                    <button name="button" type="submit" class="btn btn-primary">Update Plan</button>
                  <% end %>
                <% end %>
              </div>
              <h5>Features</h5>
              <ul class="features">
                <%= raw plan.features %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>  
</div>

<% if @subscription.plan_id.nil? %>
  <!-- Subscriptions Modal -->
  <div class="modal" id="subscription-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <%= form_tag('/subscriptions',
    role: 'form',
    class: 'payola-onestep-subscription-form',
    id: 'subscription-form',
    'data-payola-base-path' => '/payola',
    'data-payola-error-selector' => '.payola-error',
    'data-payola-plan-type' => '',
    'data-payola-plan-id' => '') do %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Subscribe</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

                <div class="form-group">
                  <label>Email Address</label>
                  <input type="email"
                         name="email"
                         data-payola="email"
                         placeholder="you@example.com"
                         class="form-control"></input>
                </div>
                <div class="form-group">
                  <label>Card number</label>
                  <input type="text"
                         size="20"
                         data-stripe="number"
                         class="card-number form-control"
                         placeholder="**** **** **** ****"></input>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Exp</label>
                      <input type="text"
                             size="8"
                             class="exp-date form-control"
                             placeholder="MM / YY"></input>
                      <input type="hidden" data-stripe="exp_month"></input>
                      <input type="hidden" data-stripe="exp_year"></input>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>CVC</label>
                      <input type="text"
                             size="4"
                             data-stripe="cvc"
                             class="form-control"
                             placeholder="***"></input>
                    </div>
                  </div>
                </div>
                <input type="hidden" name="quantity" data-payola="quantity" class="quantity" value="1">
                <div class="alert alert-warning payola-error" style="display: none"></div>
        </div>
        <div class="modal-footer">
          <input type="submit" value="Subscribe" class="btn btn-info btn-lg"></input>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

<% if @subscription.plan_id %>
  <div class="modal fade" id="update-card-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <%= form_tag(payola.update_card_path(@subscription.guid),
      role: 'form',
      class: 'update-card-form',
      id: 'update-card-form') do %>
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Update Card</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
                  <div class="form-group">
                    <label>Card number</label>
                    <input type="text"
                           size="20"
                           data-stripe="number"
                           class="card-number form-control"
                           placeholder="**** **** **** ****"></input>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label>Exp</label>
                        <input type="text"
                               size="8"
                               class="exp-date form-control"
                               placeholder="MM / YY"></input>
                        <input type="hidden" data-stripe="exp_month"></input>
                        <input type="hidden" data-stripe="exp_year"></input>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label>CVC</label>
                        <input type="text"
                               size="4"
                               data-stripe="cvc"
                               class="form-control"
                               placeholder="***"></input>
                      </div>
                    </div>
                  </div>
                  <input type="hidden" name="quantity" data-payola="quantity" class="quantity" value="1">
                  <input type="hidden" name="guid" class="subscription_guid" value="<%= @subscription.guid %>">
                  <div class="alert alert-warning payola-payment-error" style="display: none"></div>
          </div>
          <div class="modal-footer">
            <input type="submit" value="Update Card" class="btn btn-info btn-lg"></input>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>