config/routes.rb
require 'domains'

Rails.application.routes.draw do

  # Agents admin
  namespace :admin do            
    resource :account_settings, path: 'settings', :constraints => Subdomain do
      get :tickets
      get :articles
      get :canned_responses
      get :rules
      get :labels
      get :imports
      get :registration
      get :roles
      get :permission_schemes
      post :import_tickets
      post :import_users
      post :import_replies
    end
    resources :canned_responses, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :rule_sets, :constraints => Subdomain
    resources :labels, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :roles, only: [:update, :create, :destroy, :edit], :constraints => Subdomain do
      post :add_user, on: :collection
      post :remove_user, on: :collection
    end
    resources :permissions, :constraints => Subdomain
    resources :permission_schemes, :constraints => Subdomain
    resources :channel_items, :constraints => Subdomain, only: [:index, :update, :destroy], path: 'channels' do
      get :create_ticket, on: :member
      get :sync, on: :collection
    end
    resources :products, param: :slug, :constraints => Subdomain do
      get :branding, on: :member
      get :permissions, on: :member
      get :users, on: :member
      post :update_user_roles, on: :member
      get :envato, on: :member
    end
    resources :users, param: :username  do
      get :import, on: :collection
      get :sync_envato_purchases, on: :member
      resources :user_settings, path: 'settings', only: [:update, :create]
    end
    resources :categories, :constraints => Subdomain do
      # put :move_article, on: :member
      collection do
        match :sync, :via => [:get, :post]
      end
    end
    resources :tickets, :constraints => Subdomain do
      get :import, on: :collection
      get :follow, on: :member
      get :unfollow, on: :member
      patch :update_status, on: :member
      patch :assign, on: :member
      resources :replies, shallow: true
    end
    resources :articles, :constraints => Subdomain do
      post :move, on: :member
    end
    resources :sections, only: [:index, :new, :create, :update, :edit, :destroy, :show], :constraints => Subdomain do
      put :sort, on: :collection
      put :sort_articles, on: :member
      post :move, on: :member
    end
  end
  root to: "products#index", :as => 'categories_index', :constraints => Subdomain

  # Tenant frontend
  resources :tickets, :constraints => Subdomain  
  resources :media, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
  resources :categories, only: [:show, :index], :constraints => Subdomain
  resources :articles #, :only => [:show], :constraints => Subdomain
  resources :search, only: [:index], :constraints => Subdomain
  devise_for :users, path: '', controllers: { sessions: "sessions", registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  mount Payola::Engine => '/payola', as: :payola
  get 'pricing' => 'subscriptions#show', as: 'pricing'
  resource :account, only: [:new, :create]
  resource :subscription, only: [:show] do #, :constraints => RootDomain do
    # get :create
    post :cancel
    post :change_plan
    patch :update_card
    resources :subscriptions
  end
  mount StripeEvent::Engine => '/webhooks', :constraints => RootDomain
  resources :products, param: :slug, path: '/', only: [:index, :show], :constraints => Subdomain

  # Landing
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', :constraints => RootDomain
  root to: "pages#show", :slug => 'home', :constraints => RootDomain
  resources :posts, only: [:index, :show, :edit, :update], param: :slug, path: 'blog', :constraints => RootDomain
  resources :pages, only: [:show, :edit, :update], param: :slug, path: '', :constraints => RootDomain
  
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_tenant(:account)  
  has_attached_file :image
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates_presence_of :name, :slug
  resourcify
  has_many :users, through: :roles, class_name: 'User', source: :users
# has_many :users, -> (product) { includes(:roles_for_product) }, through: :roles, class_name: 'User', source: :users
# has_many :users_with_roles, -> (product) { users.with_roles_for_product(self.id).distinct(user.id) }
  def to_param
    "#{self.slug}"
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout 'admin'
  before_action :set_product, except: [:index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def users
    # @users = User.joins(:roles).where(roles: {resource_id: @product.id}).distinct.paginate(:page => params[:page])
    @users = User.includes(memberships: :role).joins(:users_roles).references(:users_roles).where(users_roles: { role_id: @product.roles.map(&:id)}).distinct.paginate(:page => params[:page])
    # abort @users[0].memberships.inspect
    @users_role = UsersRole.new
    @product_roles = @product.roles


    # places = Place.all.to_a
    
    # # 2nd query: load events for given places, matching the date condition
    # events = Event.where(place: places.map(&:id)).where("start_date > '#{time_in_the_future}'")
    # events_by_place_id = events.group_by(&:place_id)
    
    # # 3: manually set the association
    # places.each do |place|
    #   events = events_by_place_id[place.id] || []
    
    #   association = place.association(:events)
    #   association.loaded!
    #   association.target.concat(events)
    #   events.each { |event| association.set_inverse_instance(event) }
    # end
  end

  def update_user_roles
    @user = User.find(params[:product][:users].to_i)
    @roles = params[:product][:roles]
    @roles.each do |role_id|
      next if role_id.blank?
      role = Role.find_by id: role_id, resource_id: nil
      @user.add_role role.name, @product if role
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        flash[:success] = 'Product was successfully updated.'
        format.html { redirect_to edit_admin_product_path @product }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by_slug!(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.fetch(:product, {}).permit(:name,:slug,:description,:image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @categories = Category.where(product_id: @product.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by_slug!(params[:slug])
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin,@product]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :slug %>
  <%= f.input :status %>
  <%= f.input :image, :as => :image_preview, input_html: { remove_url: '#' } %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/admin/products/_sidebar.html.erb
<div class="sidebar">
	<ul class="nav flex-column nav-pills" role="tablist">
	  <%= nav_link('<i class="material-icons">brush</i> Basic', admin_product_path(@product)) %>
	  <%= nav_link('<i class="material-icons">brush</i> Branding', branding_admin_product_path(@product)) %>
	  <%= nav_link('<i class="material-icons">brush</i> Permissions', permissions_admin_product_path(@product)) %>
	  <%= nav_link('<i class="material-icons">brush</i> Users', users_admin_product_path(@product)) %>
	  <%= nav_link('<i class="material-icons">brush</i> Envato', envato_admin_product_path(@product)) %>
	</ul>
</div>

app/views/admin/products/branding.html.erb
<% content_for :page_header do %>
    <h1><%= @product.name %> -> Branding</h1>
<% end %>
<%= render 'sidebar' %>
<div class="content col-p">
    <%= render 'form', product: @product %>
</div>

app/views/admin/products/envato.html.erb
<% content_for :page_header do %>
    <h1><%= @product.name %> -> Envato</h1>
<% end %>
<%= render 'sidebar' %>
<div class="content col-p">
    <%= simple_form_for([:admin,@product], html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
        <%= f.error_notification %>
        <%= f.input :status %>
        <%= f.button :submit %>
    <% end %>
</div>

app/views/admin/products/index.html.erb
<% content_for :page_header do %>
  <h1>Products</h1>
  <div class="actions-bar">
    <%= link_to 'New Product', new_admin_product_path, class: 'btn btn-white' %>  
  </div>
<% end %>
<div class="content">
  <table class="products table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Position</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr data-url="<%= admin_product_url product %>">
          <td>
            <%= product.name %>
          </td>
          <td>
            <%#= product.position %>
          </td>
          <td class="actions">
            <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, admin_product_path(product) %>
            <%= link_to '<i class="material-icons">delete</i>'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

app/views/admin/products/permissions.html.erb
<% content_for :page_header do %>
    <h1><%= @product.name %> -> Permissions</h1>
<% end %>
<%= render 'sidebar' %>
<div class="content col-p">
    <%= simple_form_for([:admin,@product], html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, collection: Role.all, input_html: { class: 'select-tags' } %>
        <%= f.input :slug %>
        <%= f.input :status %>
        <%= f.button :submit %>
    <% end %>
</div>

app/views/admin/products/show.html.erb
<% content_for :page_header do %>
    <h1><%= @product.name %></h1>
<% end %>
<%= render 'sidebar' %>
<div class="content col-p">
    <%= render 'form', product: @product %>
</div>

app/views/admin/products/users.html.erb
<% content_for :page_header do %>
    <h1><%= @product.name %> -> Users</h1>
    <div class="actions-bar">
        <%= link_to 'Add User', '#', class: 'btn btn-white' %>
    </div>
<% end %>
<%= render 'sidebar' %>
<div class="content col-p">
    <table class="table table-hover mb-0 users">
    <thead>
        <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Created</th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr data-url="<%= admin_user_path user.username %>" class="user">
            <td><span class="mr-3"><%= raw user.avatar %></span><%= user.display_name %></td>
            <td><%= user.email %></td>
            <td>
                <% user.memberships.each do |membership|%>
                    <% next if !@product_roles.map(&:id).include? membership.role_id %>
                    <%= membership.badge %>
                <% end %>
                <%= simple_form_for [:admin,@product], :url => update_user_roles_admin_product_path, :method => :post do |f| %>
                <% end %> 
            </td>
            <td><%= time_format user.created_at %></td>
        </tr>
        <% end %>
    </tbody>
    </table>

    <%= will_paginate @users %>

    <%= simple_form_for [:admin,@users_role], :url => add_user_admin_roles_path, :method => :post do |f| %>
        <input type="hidden" name="product_id" value="<%= @product.id %>">
        <%= f.input :user_id, collection: User.all, :include_blank => false, :label_method => lambda { |user| "#{user.display_name}" } %>
        <%= f.input :role_id, collection: Role.available, :value_method => lambda { |role| "#{role.name}"}, :include_blank => false, input_html: { name: 'users_role[role][]', multiple: true, class: 'select-tags' } %>
        <%= f.button :submit, value: 'Add User' %>
    <% end %>

</div>