config/routes.rb
require 'domains'

Rails.application.routes.draw do

  # Agents admin
  namespace :admin do            
    resource :account_settings, path: 'settings', :constraints => Subdomain do
      get :tickets
      get :articles
      get :canned_responses
      get :rules
      get :labels
      get :imports
      get :registration
      get :roles
      get :permission_schemes
      post :import_tickets
      post :import_users
      post :import_replies
    end
    resources :canned_responses, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :rule_sets, :constraints => Subdomain
    resources :labels, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
    resources :roles, only: [:update, :create, :destroy, :edit], :constraints => Subdomain do
      post :add_user, on: :collection
      post :remove_user, on: :collection
    end
    resources :permissions, :constraints => Subdomain
    resources :permission_schemes, :constraints => Subdomain
    resources :channel_items, :constraints => Subdomain, only: [:index, :update, :destroy], path: 'channels' do
      get :create_ticket, on: :member
      get :sync, on: :collection
    end
    resources :products, param: :slug, :constraints => Subdomain do
      get :branding, on: :member
      get :permissions, on: :member
      get :users, on: :member
      post :update_user_roles, on: :member
      get :envato, on: :member
    end
    resources :users, param: :username  do
      get :import, on: :collection
      get :sync_envato_purchases, on: :member
      resources :user_settings, path: 'settings', only: [:update, :create]
    end
    resources :categories, :constraints => Subdomain do
      # put :move_article, on: :member
      collection do
        match :sync, :via => [:get, :post]
      end
    end
    resources :tickets, :constraints => Subdomain do
      get :import, on: :collection
      get :follow, on: :member
      get :unfollow, on: :member
      patch :update_status, on: :member
      patch :assign, on: :member
      resources :replies, shallow: true
    end
    resources :articles, :constraints => Subdomain do
      post :move, on: :member
    end
    resources :sections, only: [:index, :new, :create, :update, :edit, :destroy, :show], :constraints => Subdomain do
      put :sort, on: :collection
      put :sort_articles, on: :member
      post :move, on: :member
    end
  end
  root to: "products#index", :as => 'categories_index', :constraints => Subdomain

  # Tenant frontend
  resources :tickets, :constraints => Subdomain  
  resources :media, only: [:update, :create, :destroy, :edit], :constraints => Subdomain
  resources :categories, only: [:show, :index], :constraints => Subdomain
  resources :articles #, :only => [:show], :constraints => Subdomain
  resources :search, only: [:index], :constraints => Subdomain
  devise_for :users, path: '', controllers: { sessions: "sessions", registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  mount Payola::Engine => '/payola', as: :payola
  get 'pricing' => 'subscriptions#show', as: 'pricing'
  resource :account, only: [:new, :create]
  resource :subscription, only: [:show] do #, :constraints => RootDomain do
    # get :create
    post :cancel
    post :change_plan
    patch :update_card
    resources :subscriptions
  end
  mount StripeEvent::Engine => '/webhooks', :constraints => RootDomain
  resources :products, param: :slug, path: '/', only: [:index, :show], :constraints => Subdomain

  # Landing
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', :constraints => RootDomain
  root to: "pages#show", :slug => 'home', :constraints => RootDomain
  resources :posts, only: [:index, :show, :edit, :update], param: :slug, path: 'blog', :constraints => RootDomain
  resources :pages, only: [:show, :edit, :update], param: :slug, path: '', :constraints => RootDomain
  
end

app/models/category.rb
class Category < ApplicationRecord
	include HasRules
	# Relationships
	acts_as_tenant(:account)
	belongs_to :product
	has_many :tickets
	has_many :purchases
	has_many :channel_items
	has_many :users, through: :purchases
	# has_many :articles_items
	has_many :sections
	has_and_belongs_to_many :articles
	has_attached_file :image
	has_and_belongs_to_many :rule_sets
	enum status: {
			draft: 0,
			published: 1,
	}

	# Validation
	validates :name, :slug, presence: true
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_uniqueness_to_tenant :slug
  validates_uniqueness_to_tenant :external_id, unless: Proc.new { |item| item.external_id.nil? }

  def to_param
    "#{id}-#{self.name.parameterize}"
  end

	def to_label
	  "#{name}"
	end

	def slug=(value)
	  if value.present?
	    write_attribute(:slug, value.parameterize)
      else
	    write_attribute(:slug, self.name.parameterize)
	  end
	end

	def image_from_url(url)
	  self.image = URI.parse(url)
	end

	def self.allowed_rule_keys
		self.attribute_names
	end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'admin'
  include RequireTenant
  # load_and_authorize_resource
  before_action :set_category, only: [:show, :update, :destroy, :edit]
  after_action except: [:index] { authorize @category }
  after_action only:   [:index] { authorize @categories }

  # GET /categories
  # GET /categories.json
  def index
    @category = Category.new
    @categories = policy_scope(Category).includes(:sections).paginate(:page => params[:page])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @sections = Section.where(category_id: @category.id)
    @categories = policy_scope(Category).includes(:sections)    
  end

  # PUT /categories/1/move_article
  def move_article
    @article_category = ArticlesCategory.find_by(category_id: params[:id], article_id: params[:article_id].to_i)
    @article_category.section_id = params[:section_id].to_i
    if @article_item.save
      render :success => true
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to show_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /categories/sync
  def sync
    envato_items = current_user.get_envato_items
    envato_items.each do |envato_item|
      @categories = Category.find_or_create_by(external_id: envato_item['id'], source: 'envato') do |category|
        category.name = envato_item['name']
        category.slug = envato_item['name'].parameterize
        category.image = open(envato_item['previews']['icon_with_landscape_preview']['landscape_url'])
      end
    end
    if @categories.errors.any?
      flash[:error] = @categories.errors.join("<br>")
    else
      flash[:success] = 'categories synced.'
    end
    redirect_to categories_account_settings_path
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to show_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category, {}).permit(:name, :slug, :external_id, :source, :status, :rule_set_ids => [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include RequireTenant
  before_action :set_category, only: [:show, :update, :destroy, :edit]

  # GET /categories/1
  # GET /categories/1.json
  def show
    @sections = Section.where(category_id: @category.id)
    @categories = policy_scope(Category).includes(:sections)    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.input :slug %>
  <%= f.association :rule_sets %>
  <%= f.input :external_id, label: "Envato ID" %>
  <%= f.input :status %>
  <%= f.input :image, as: :image_preview %>
  <%= f.button :submit %>
<% end %>

app/views/categories/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr data-id="<%= item.id %>">
        <td><%= item.name %></td>
        <td>
          <div class="actions">
            <%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_item_path(item) %>
            <%= link_to '<i class="material-icons">delete</i>'.html_safe, item, method: :delete, remote: true, data: { confirm: 'Are you sure you want to delete this item and all its tickets?' } %>    
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/_sort.html.erb
<%= link_to 'New Article', new_article_path, :class => 'btn btn-primary' %>
<div class="sections row sort" id="sections" data-item-id="<%= @item.id %>" data-role="activerecord_sortable">
	<% @sections.each do |section| %>
	  <div class="section section-draggable col-md-12"  data-id="<%= section.id %>" data-sort-order="0" data-role="section<%= section.id %>" data-move-url="<%= move_section_url(section) %>" data-position="<%= section.position %>">
	  	<div class="section-title">
	  		<h4><%= section.name %></h4>
	  		<td><%= link_to 'Edit', edit_section_path(section) %></td>
	  		<td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  	</div>
		<div class="articles sort" data-section-id="<%= section.id %>" data-role="activerecord_sortable">
			<% section.articles.each do |article| %>
				<div class="article" data-id="<%= article.id %>" data-sort-order="0" data-role="article<%= article.id %>" data-move-url="<%= move_article_url(article) %>" data-position="<%= article.position %>">
					<%= link_to article.title, article %>
					<%= link_to 'Edit', edit_article_path(article) %>
					<%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
			<% end %>
		</div>
	  </div>
	<% end %>
</div>

app/views/categories/_sort2.html.erb
<%= link_to 'New Article', new_article_path, :class => 'btn btn-primary' %>
<div class="sections row sort" id="sections" data-item-id="<%= @item.id %>">
	<% @item.sections.each do |section| %>
	  <div class="section section-draggable col-md-4"  data-id="<%= section.id %>" data-sort-order="0">
	  	<div class="section-title">
	  		<h4><%= section.name %></h4>
	  		<td><%= link_to 'Edit', edit_section_path(section) %></td>
	  		<td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  	</div>
		<div class="articles sort" data-section-id="<%= section.id %>">
			<% section.articles.each do |article| %>
				<div class="article" data-id="<%= article.id %>" data-sort-order="0">
					<%= link_to article.title, article %>
					<%= link_to 'Edit', edit_article_path(article) %>
					<%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
			<% end %>
		</div>
	  </div>
	<% end %>
</div>

app/views/categories/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 offset-md-4">
			<div class="page-header">
				<h1>Editing Item</h1>
				<div class="actions-bar">
					<%= link_to 'Back', items_index_url, :class => 'btn' %>
				</div>
			</div>
			<div class="card">
				<div class="card-block">
					<%= render 'form', item: @item %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= @settings.branding_company_name %> Support</h1>
<!--     <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
    <p>
    <%= render 'search' %>
    </p>
  </div>
</section>

<div class="container">
  <div class="categories row">
    <% @categories.each do |category| %>
      <div class="category col-lg-4 col-md-6 col-sm-6 mb-5">

        <div class="card">
          <% if category.image.file? %>
            <%= link_to image_tag(category.image.url, :class => 'card-img-top', :alt => category.name), category_path(category) %>
          <% end %>
          <div class="card-block">
            <h5 class="card-title"><%= link_to category.name, category_path(category) %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 offset-md-4">
			<div class="page-header">
				<h1>New Item</h1>
			</div>
			<div class="card">
				<div class="card-block">
					<%= render 'form', item: @item %>					
				</div>
			</div>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= @category.name %></h1>
    <%#= render 'search', product_id: @product.id %>
  </div>
</section>

<%= render 'sections/table' %>